#!/usr/bin/env tsx
/**
 * Composes per-layer Firestore + Storage rule fragments into the root
 * firestore.rules and storage.rules files.
 *
 * Layer order: 'core' first, then alphabetical for everything else.
 *
 * Fragments must NOT contain `rules_version` or `service` lines — the
 * composer emits the outer envelope and shared helpers.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const LAYERS_DIR = join(ROOT, 'layers')

const BANNER = `// AUTO-GENERATED by scripts/compose-rules.ts.
// Edit layers/<name>/firestore.rules.frag (or storage.rules.frag) and run \`pnpm rules:compose\`.

`

const FIRESTORE_HELPERS = `    function isSignedIn()    { return request.auth != null; }
    function claimOrgId()    { return request.auth.token.orgId; }
    function claimRole()     { return request.auth.token.role; }
    function inOrg(orgId)    { return isSignedIn() && claimOrgId() == orgId; }
    function hasRole(roles)  { return isSignedIn() && claimRole() in roles; }

`

function discoverLayers(): string[] {
  const all = readdirSync(LAYERS_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()
  if (!all.includes('core')) {
    throw new Error('compose-rules: layers/core not found')
  }
  return ['core', ...all.filter((n) => n !== 'core')]
}

function loadFragment(layer: string, kind: 'firestore' | 'storage'): string | null {
  const path = join(LAYERS_DIR, layer, `${kind}.rules.frag`)
  if (!existsSync(path)) return null
  const content = readFileSync(path, 'utf8')
  if (/^\s*rules_version\b/m.test(content) || /^\s*service\s+/m.test(content)) {
    throw new Error(
      `${path}: fragment must not contain 'rules_version' or 'service' — composer emits the envelope.`,
    )
  }
  return content
}

function composeFirestore(): string {
  const layers = discoverLayers()
  const fragments = layers
    .map((l) => ({ layer: l, body: loadFragment(l, 'firestore') }))
    .filter((f): f is { layer: string; body: string } => f.body !== null)
  const inner = fragments
    .map((f) => `    // ─── ${f.layer} layer fragment ───\n${f.body}`)
    .join('\n')
  return `${BANNER}rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {

${FIRESTORE_HELPERS}${inner}
  }
}
`
}

function composeStorage(): string {
  const layers = discoverLayers()
  const fragments = layers
    .map((l) => ({ layer: l, body: loadFragment(l, 'storage') }))
    .filter((f): f is { layer: string; body: string } => f.body !== null)
  const inner = fragments
    .map((f) => `    // ─── ${f.layer} layer fragment ───\n${f.body}`)
    .join('\n')
  return `${BANNER}rules_version = '2';

service firebase.storage {
  match /b/{bucket}/o {
${inner}
  }
}
`
}

writeFileSync(join(ROOT, 'firestore.rules'), composeFirestore())
writeFileSync(join(ROOT, 'storage.rules'), composeStorage())
console.log('Composed firestore.rules and storage.rules')
